name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - test

permissions:
  contents: write
  packages: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: build
        run: nx run-many -t build
      # -----------------------------
      # beta（merge → test）
      # -----------------------------
      - name: Version (beta)
        if: github.base_ref == 'test'
        run: |
          npx changeset pre exit || true
          npx changeset pre enter beta
          npx changeset version
          npx changeset pre exit

      - name: Publish (beta)
        if: github.base_ref == 'test'
        run: npx changeset publish --tag beta
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # -----------------------------
      # latest（merge → master）
      # -----------------------------
      - name: Version (latest)
        if: github.base_ref == 'master'
        run: npx changeset version

      - name: Publish (latest)
        if: github.base_ref == 'master'
        run: npx changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # -----------------------------
      # push version & tags
      # -----------------------------
      - name: Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore: release" || exit 0
          git push origin HEAD:${{ github.base_ref }}
          git push origin --tags